site_name: ArXiv Tracker
theme:
  name: material
  features:
  - navigation.tabs
  - search.suggest
  - search.highlight
  navigation_depth: 0
  toc_depth: 0
  language: zh
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: teal
    accent: purple
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: teal
    accent: lime
markdown_extensions:
- toc:
    permalink: false
    toc_depth: 0
extra:
  generator: false
nav:
- Home: index.md
- Emission Trading System:
  - 2024-09(1): Emission Trading System/2024/09.md
  - 2024-08(3): Emission Trading System/2024/08.md
  - 2024-07(1): Emission Trading System/2024/07.md
  - 2024-06(1): Emission Trading System/2024/06.md
  - 2024-03(1): Emission Trading System/2024/03.md
  - 2024-02(1): Emission Trading System/2024/02.md
  - 2024-01(2): Emission Trading System/2024/01.md
  - 2023-12(1): Emission Trading System/2023/12.md
  - 2023-10(1): Emission Trading System/2023/10.md
  - 2023-09(1): Emission Trading System/2023/09.md
  - 2023-06(2): Emission Trading System/2023/06.md
  - 2023-05(1): Emission Trading System/2023/05.md
  - 2023-03(3): Emission Trading System/2023/03.md
  - 2022-12(1): Emission Trading System/2022/12.md
  - 2022-11(1): Emission Trading System/2022/11.md
  - 2022-10(1): Emission Trading System/2022/10.md
  - 2022-06(1): Emission Trading System/2022/06.md
  - 2022-02(2): Emission Trading System/2022/02.md
  - 2021-11(1): Emission Trading System/2021/11.md
  - 2021-10(1): Emission Trading System/2021/10.md
  - 2021-07(1): Emission Trading System/2021/07.md
  - 2021-05(1): Emission Trading System/2021/05.md
  - 2021-04(1): Emission Trading System/2021/04.md
  - 2021-02(1): Emission Trading System/2021/02.md
  - 2020-11(1): Emission Trading System/2020/11.md
  - 2020-10(2): Emission Trading System/2020/10.md
  - 2020-08(2): Emission Trading System/2020/08.md
  - 2020-07(1): Emission Trading System/2020/07.md
  - 2020-05(1): Emission Trading System/2020/05.md
  - 2020-03(1): Emission Trading System/2020/03.md
  - 2020-01(1): Emission Trading System/2020/01.md
  - 2019-11(1): Emission Trading System/2019/11.md
  - 2019-08(1): Emission Trading System/2019/08.md
  - 2018-12(1): Emission Trading System/2018/12.md
  - 2018-10(1): Emission Trading System/2018/10.md
  - 2018-08(1): Emission Trading System/2018/08.md
  - 2016-09(1): Emission Trading System/2016/09.md
  - 2015-08(1): Emission Trading System/2015/08.md
  - 2015-02(1): Emission Trading System/2015/02.md
  - 2011-10(1): Emission Trading System/2011/10.md
- Retrieval Augmented Generation:
  - 2024-09(17): Retrieval Augmented Generation/2024/09.md
  - 2024-08(115): Retrieval Augmented Generation/2024/08.md
  - 2024-07(134): Retrieval Augmented Generation/2024/07.md
  - 2024-06(161): Retrieval Augmented Generation/2024/06.md
  - 2024-05(126): Retrieval Augmented Generation/2024/05.md
  - 2024-04(86): Retrieval Augmented Generation/2024/04.md
  - 2024-03(70): Retrieval Augmented Generation/2024/03.md
  - 2024-02(87): Retrieval Augmented Generation/2024/02.md
  - 2024-01(50): Retrieval Augmented Generation/2024/01.md
  - 2023-12(33): Retrieval Augmented Generation/2023/12.md
  - 2023-11(38): Retrieval Augmented Generation/2023/11.md
  - 2023-10(43): Retrieval Augmented Generation/2023/10.md
  - 2023-09(20): Retrieval Augmented Generation/2023/09.md
  - 2023-08(13): Retrieval Augmented Generation/2023/08.md
  - 2023-07(11): Retrieval Augmented Generation/2023/07.md
  - 2023-06(12): Retrieval Augmented Generation/2023/06.md
  - 2023-05(33): Retrieval Augmented Generation/2023/05.md
  - 2023-04(10): Retrieval Augmented Generation/2023/04.md
  - 2023-03(7): Retrieval Augmented Generation/2023/03.md
  - 2023-02(10): Retrieval Augmented Generation/2023/02.md
  - 2023-01(3): Retrieval Augmented Generation/2023/01.md
  - 2022-12(12): Retrieval Augmented Generation/2022/12.md
  - 2022-11(6): Retrieval Augmented Generation/2022/11.md
  - 2022-10(15): Retrieval Augmented Generation/2022/10.md
  - 2022-09(3): Retrieval Augmented Generation/2022/09.md
  - 2022-08(3): Retrieval Augmented Generation/2022/08.md
  - 2022-07(7): Retrieval Augmented Generation/2022/07.md
  - 2022-06(3): Retrieval Augmented Generation/2022/06.md
  - 2022-05(6): Retrieval Augmented Generation/2022/05.md
  - 2022-04(10): Retrieval Augmented Generation/2022/04.md
  - 2022-03(2): Retrieval Augmented Generation/2022/03.md
  - 2022-02(4): Retrieval Augmented Generation/2022/02.md
  - 2022-01(3): Retrieval Augmented Generation/2022/01.md
  - 2021-12(9): Retrieval Augmented Generation/2021/12.md
  - 2021-11(2): Retrieval Augmented Generation/2021/11.md
  - 2021-10(5): Retrieval Augmented Generation/2021/10.md
  - 2021-09(4): Retrieval Augmented Generation/2021/09.md
  - 2021-08(7): Retrieval Augmented Generation/2021/08.md
  - 2021-06(7): Retrieval Augmented Generation/2021/06.md
  - 2021-05(2): Retrieval Augmented Generation/2021/05.md
  - 2021-04(2): Retrieval Augmented Generation/2021/04.md
  - 2021-03(1): Retrieval Augmented Generation/2021/03.md
  - 2021-02(3): Retrieval Augmented Generation/2021/02.md
  - 2021-01(2): Retrieval Augmented Generation/2021/01.md
  - 2020-12(1): Retrieval Augmented Generation/2020/12.md
  - 2020-11(2): Retrieval Augmented Generation/2020/11.md
  - 2020-10(3): Retrieval Augmented Generation/2020/10.md
  - 2020-09(2): Retrieval Augmented Generation/2020/09.md
  - 2020-08(3): Retrieval Augmented Generation/2020/08.md
  - 2020-07(3): Retrieval Augmented Generation/2020/07.md
  - 2020-06(3): Retrieval Augmented Generation/2020/06.md
  - 2020-05(1): Retrieval Augmented Generation/2020/05.md
  - 2020-04(5): Retrieval Augmented Generation/2020/04.md
  - 2020-03(2): Retrieval Augmented Generation/2020/03.md
  - 2020-02(2): Retrieval Augmented Generation/2020/02.md
  - 2020-01(1): Retrieval Augmented Generation/2020/01.md
  - 2019-12(2): Retrieval Augmented Generation/2019/12.md
  - 2019-11(1): Retrieval Augmented Generation/2019/11.md
  - 2019-09(2): Retrieval Augmented Generation/2019/09.md
  - 2019-06(2): Retrieval Augmented Generation/2019/06.md
  - 2019-05(1): Retrieval Augmented Generation/2019/05.md
  - 2019-04(1): Retrieval Augmented Generation/2019/04.md
  - 2019-02(2): Retrieval Augmented Generation/2019/02.md
  - 2018-11(3): Retrieval Augmented Generation/2018/11.md
  - 2018-09(1): Retrieval Augmented Generation/2018/09.md
  - 2018-02(2): Retrieval Augmented Generation/2018/02.md
  - 2018-01(1): Retrieval Augmented Generation/2018/01.md
  - 2017-12(1): Retrieval Augmented Generation/2017/12.md
  - 2017-09(1): Retrieval Augmented Generation/2017/09.md
  - 2017-07(1): Retrieval Augmented Generation/2017/07.md
  - 2016-10(1): Retrieval Augmented Generation/2016/10.md
  - 2016-08(1): Retrieval Augmented Generation/2016/08.md
  - 2016-07(1): Retrieval Augmented Generation/2016/07.md
  - 2016-05(1): Retrieval Augmented Generation/2016/05.md
  - 2016-04(1): Retrieval Augmented Generation/2016/04.md
  - 2016-01(1): Retrieval Augmented Generation/2016/01.md
  - 2015-11(1): Retrieval Augmented Generation/2015/11.md
  - 2014-11(1): Retrieval Augmented Generation/2014/11.md
  - 2014-03(1): Retrieval Augmented Generation/2014/03.md
  - 2012-01(1): Retrieval Augmented Generation/2012/01.md
  - 2009-03(1): Retrieval Augmented Generation/2009/03.md
plugins:
- search
